let vari = 1;
console.log(vari);
let string=String(vari);
console.log(string);
let bvar=Boolean(string);
console.log(bvar);
bvar=Boolean(vari);
console.log(bvar);
let dt=Number(new Date());
console.log(dt);
dt=String(new Date());
console.log(dt);
stri = Number("12s3");
console.log(stri);
stri = Number([1,2,3,4,5,6,7,8,9]);
console.log(stri);
stri = Number(false);
console.log(stri);
stri = String([1,2,3,4,5,6,7,8,9]);
console.log(stri);
stri = Boolean([1,2,3,4,5,6,7,8,9]);
console.log(stri);

let num='21.342222';
let subnum=parseInt(num);
console.log(subnum);
subnum=parseFloat(num);
console.log(subnum);
console.log(subnum.toFixed(10),(typeof subnum));
